sptx-format: remove uses of validate_sptx/validate-sptx
0.0.28 is missing the schema json files for sptx-format leading
to the error:

```
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/sptx_format/util.py", line 51, in load_json
    with open(json_file, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory:
    '/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/sptx_format/schema/experiment.json'
make: *** [run__notebooks/py/assay_comparison.py] Error 1
```

see: gh-717